# Generated by Django 4.1.5 on 2023-02-03 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='path_to_tlg_session_file',
        ),
    ]
