# Generated by Django 4.1.5 on 2023-02-03 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_path_to_tlg_session_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='path_to_tlg_session_file',
            field=models.FileField(null=True, upload_to='session_files/', verbose_name='Файл сессии'),
        ),
    ]
