# Generated by Django 4.1.5 on 2023-02-03 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_path_to_tlg_session_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='path_to_tlg_session_file',
            new_name='tlg_session_file',
        ),
    ]
