# Generated by Django 4.1.5 on 2023-02-03 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_path_to_tlg_session_file_profile_tlg_session_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='deflt_mlng_txt',
            field=models.CharField(default='Это стандартное сообщение, которое будет предустановлено по дефолту. В нём будет,к примеру, изменена текущая дата и время. Вот: 2023-02-03 22:50:04.248201', max_length=500, verbose_name='Стандартный текст рассылки'),
        ),
    ]
