# Generated by Django 4.1.5 on 2023-02-04 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_profile_deflt_mlng_txt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='deflt_mlng_txt',
            field=models.TextField(default='Это стандартное сообщение, которое будет предустановлено по дефолту. В нём будет,к примеру, изменена текущая дата и время. Вот: {datetime}. Ну и давайте сумму долга обработаем: {debt}', max_length=500, verbose_name='Стандартный текст рассылки'),
        ),
    ]
