# Generated by Django 4.1.5 on 2023-02-04 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_profile_deflt_mlng_txt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='deflt_mlng_txt',
            new_name='dflt_mlng_txt',
        ),
    ]
