# Generated by Django 4.1.5 on 2023-02-08 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_rename_deflt_mlng_txt_profile_dflt_mlng_txt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dflt_mlng_txt',
            field=models.TextField(default='Здравствуйте, {client}!\nНапоминаем, что {date} очередной платеж в размере {debt} рублей. Хорошего дня!', max_length=500, verbose_name='Стандартный текст рассылки'),
        ),
    ]
