# Generated by Django 4.1.5 on 2023-02-21 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_profile_dflt_mlng_txt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dflt_mlng_txt',
            field=models.TextField(default='Здравствуйте, {client}!\nВас приветствует {my_comp}.\nНапоминаем, что {date} очередной платеж в размере {amount} рублей. Хорошего дня!\n🐦', max_length=500, verbose_name='Стандартный текст рассылки'),
        ),
    ]
