# Generated by Django 4.1.5 on 2023-03-06 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_profile_dflt_mlng_txt'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tlg_acc_info',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Инфо о Telegram аккаунте'),
        ),
    ]
