# Generated by Django 4.1.5 on 2023-03-06 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_profile_tlg_acc_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='tlg_session_file',
            field=models.FileField(blank=True, null=True, upload_to='session_files/', verbose_name='Файл сессии'),
        ),
    ]
