# Generated by Django 4.1.5 on 2023-03-16 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_profile_tlg_session_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='green_api_id_instance',
            field=models.CharField(blank=True, max_length=200, verbose_name='IdInstance'),
        ),
        migrations.AddField(
            model_name='profile',
            name='green_api_token_instance',
            field=models.CharField(blank=True, max_length=400, verbose_name='ApiTokenInstance'),
        ),
        migrations.AddField(
            model_name='profile',
            name='mailing_channel',
            field=models.CharField(choices=[('tlg', 'Telegram'), ('whtsp', 'WhatsApp')], max_length=50, null=True, verbose_name='Мессенджер для рассылки'),
        ),
    ]
