# Generated by Django 4.1.5 on 2023-03-16 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_profile_green_api_id_instance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='green_api_token_instance',
            field=models.CharField(blank=True, max_length=200, verbose_name='ApiTokenInstance'),
        ),
    ]
