# Generated by Django 4.1.5 on 2023-03-16 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_profile_green_api_token_instance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='green_api_token_instance',
            field=models.CharField(default='tlg', max_length=200, verbose_name='ApiTokenInstance'),
        ),
    ]
