# Generated by Django 4.1.5 on 2023-03-22 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_alter_profile_green_api_token_instance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='api_token_for_1c',
            field=models.CharField(max_length=50, null=True, verbose_name='1C API Token'),
        ),
    ]
