# Generated by Django 4.1.5 on 2023-03-29 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_profile_api_token_for_1c'),
    ]

    operations = [
        migrations.CreateModel(
            name='DyatelSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, verbose_name='Ключ')),
                ('value', models.TextField(max_length=1000, verbose_name='Значение')),
            ],
            options={
                'verbose_name': 'Настройка',
                'verbose_name_plural': 'Настройки',
                'ordering': ['-id'],
            },
        ),
    ]
