# Generated by Django 4.1.5 on 2023-04-04 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='reserved_for_mailing',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Зарезервировано под рассылку'),
        ),
    ]
