# Generated by Django 4.1.5 on 2023-04-05 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_profile_reserved_for_mailing'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='description',
            field=models.CharField(max_length=250, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='invoice_id',
            field=models.CharField(max_length=150, null=True, verbose_name='Номер счёта'),
        ),
    ]
