# Generated by Django 4.1.5 on 2023-04-05 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_transaction_description_alter_transaction_invoice_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='invoice_id',
        ),
    ]
