# Generated by Django 4.1.5 on 2023-04-05 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_remove_transaction_invoice_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_datetime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата и время транзакции'),
        ),
    ]
