# Generated by Django 4.1.5 on 2023-04-05 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_alter_transaction_transaction_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.TextField(max_length=250, null=True, verbose_name='Описание'),
        ),
    ]
