# Generated by Django 4.1.5 on 2023-04-11 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_alter_dyatelsettings_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dyatelsettings',
            name='value',
            field=models.TextField(max_length=23000, verbose_name='Значение'),
        ),
    ]
