# Generated by Django 4.1.5 on 2023-04-17 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_alter_dyatelsettings_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=23, verbose_name='телефон')),
                ('code', models.CharField(max_length=4, verbose_name='код')),
                ('expired_at', models.FloatField(default=1681723087.205565, verbose_name='когда истекает(сек.)')),
                ('input_attempts', models.IntegerField(default=5, verbose_name='попытки для ввода кода')),
                ('already_registered', models.BooleanField(default=False, verbose_name='Уже зарегистрирован')),
            ],
            options={
                'verbose_name': 'СМС код',
                'verbose_name_plural': 'СМС коды',
                'ordering': ['-pk'],
            },
        ),
    ]
