# Generated by Django 4.1.5 on 2023-04-18 10:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0034_smscode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smscode',
            name='expired_at',
            field=models.FloatField(default=1681813342.3380945, verbose_name='когда истекает(сек.)'),
        ),
        migrations.CreateModel(
            name='PaymentsInvoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('description', models.TextField(max_length=1000, verbose_name='Описание')),
                ('payment_url', models.URLField(blank=True, max_length=100, verbose_name='Ссылка на оплату')),
                ('pass_1_hash', models.CharField(blank=True, max_length=100, verbose_name='Хэш из пароля 1')),
                ('pass_2_hash', models.CharField(blank=True, max_length=100, verbose_name='Хэш из пароля 2')),
                ('is_paid', models.BooleanField(default=False, verbose_name='оплачен')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Счёт на оплату',
                'verbose_name_plural': 'Счета на оплату',
                'ordering': ['-pk'],
            },
        ),
    ]
