# Generated by Django 4.1.5 on 2023-04-18 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_alter_smscode_expired_at_paymentsinvoices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentsinvoices',
            name='payment_url',
            field=models.URLField(blank=True, max_length=1000, verbose_name='Ссылка на оплату'),
        ),
        migrations.AlterField(
            model_name='smscode',
            name='expired_at',
            field=models.FloatField(default=1681813556.306999, verbose_name='когда истекает(сек.)'),
        ),
    ]
