# Generated by Django 4.1.5 on 2023-04-18 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_alter_paymentsinvoices_payment_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentsinvoices',
            name='pass_2_hash',
        ),
        migrations.AlterField(
            model_name='smscode',
            name='expired_at',
            field=models.FloatField(default=1681815351.5228639, verbose_name='когда истекает(сек.)'),
        ),
    ]
