# Generated by Django 4.1.5 on 2023-02-03 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100, verbose_name='Клиент')),
                ('telephone_or_username', models.CharField(max_length=100, verbose_name='Телефон/@username')),
                ('custom_mlng_txt', models.CharField(max_length=500, verbose_name='Пользовательский текст рассылки')),
                ('amount_of_pmnt', models.FloatField(verbose_name='Сумма платежа')),
                ('pmnt_date', models.DateField(verbose_name='Дата платежа')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile', verbose_name='Пользователь сайта')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'db_table': 'Клиенты пользователей сайта',
                'ordering': ['-pmnt_date'],
            },
        ),
        migrations.CreateModel(
            name='Mailings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mlng_txt', models.CharField(max_length=500, verbose_name='Текст рассылки')),
                ('sent_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Дата и время отправки')),
                ('sending_status', models.CharField(choices=[('queued', 'в очереди'), ('cmplt', 'отправлено'), ('cncld', 'не отправлено')], default='queued', max_length=6, verbose_name='Статус отправки')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_collector.clients', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
                'db_table': 'Рассылки пользователей сайта',
                'ordering': ['-sent_datetime'],
            },
        ),
    ]
