# Generated by Django 4.1.5 on 2023-02-06 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_collector', '0002_alter_clients_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailings',
            options={'ordering': ['-id'], 'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылки'},
        ),
        migrations.AlterField(
            model_name='clients',
            name='custom_mlng_txt',
            field=models.TextField(max_length=500, verbose_name='Пользовательский текст рассылки'),
        ),
        migrations.AlterField(
            model_name='mailings',
            name='mlng_txt',
            field=models.TextField(max_length=500, verbose_name='Текст рассылки'),
        ),
    ]
