# Generated by Django 4.1.5 on 2023-02-06 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_collector', '0003_alter_mailings_options_alter_clients_custom_mlng_txt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='custom_mlng_txt',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Пользовательский текст рассылки'),
        ),
    ]
