# Generated by Django 4.1.5 on 2023-02-07 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_collector', '0004_alter_clients_custom_mlng_txt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='amount_of_pmnt',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма платежа'),
        ),
    ]
