# Generated by Django 4.1.5 on 2023-02-16 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_collector', '0005_alter_clients_amount_of_pmnt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='amount_of_pmnt',
            field=models.DecimalField(decimal_places=2, max_digits=30, verbose_name='Сумма платежа'),
        ),
    ]
