# Generated by Django 4.1.5 on 2023-02-17 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_collector', '0006_alter_clients_amount_of_pmnt'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyValueStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=2000, verbose_name='ключ')),
                ('value', models.CharField(max_length=2000, verbose_name='значение')),
            ],
            options={
                'verbose_name': 'Хранилище key-value',
                'verbose_name_plural': 'Хранилище key-value',
                'ordering': ['-id'],
            },
        ),
    ]
