# Generated by Django 4.1.5 on 2023-02-21 08:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_collector', '0007_keyvaluestorage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_text', models.TextField(max_length=1000, verbose_name='Текст фидбэка')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время фидбэка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Фидбэк пользователя',
                'verbose_name_plural': 'Фидбэки пользователей',
                'ordering': ['-id'],
            },
        ),
        migrations.DeleteModel(
            name='KeyValueStorage',
        ),
    ]
