# Generated by Django 4.1.5 on 2023-02-21 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_collector', '0008_feedback_delete_keyvaluestorage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='datetime',
            new_name='send_datetime',
        ),
    ]
