# Generated by Django 4.1.5 on 2023-03-30 10:28

import app_collector.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_collector', '0011_alter_mailings_sending_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientsFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=app_collector.models.generate_path_to_clients_files, verbose_name='Файл')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients_file', to='app_collector.clients', verbose_name='Объект клиента')),
            ],
        ),
    ]
