# Generated by Django 4.1.5 on 2023-03-30 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_collector', '0012_clientsfiles'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientsfiles',
            options={'ordering': ['-id'], 'verbose_name': 'Файл клиента', 'verbose_name_plural': 'Файлы клиента'},
        ),
        migrations.AddField(
            model_name='clientsfiles',
            name='file_size',
            field=models.FloatField(default=0, verbose_name='Размер файла'),
        ),
    ]
