# Generated by Django 4.1.5 on 2023-03-31 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_collector', '0013_alter_clientsfiles_options_clientsfiles_file_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientsfiles',
            name='file_name',
            field=models.CharField(default=111, max_length=100, verbose_name='Имя файла'),
            preserve_default=False,
        ),
    ]
