# Generated by Django 4.1.5 on 2023-04-13 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_collector', '0014_clientsfiles_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='pmnt_date',
            field=models.DateTimeField(verbose_name='Дата и время платежа'),
        ),
    ]
